zhijianzou10/my-zone

README.md

Check out the first change of read me

first change to read me

---

README.md

add fdsfqsfd

---

Gemfile
Gemfile.lock
app/policies/application_policy.rb

added pundit into rails

---

app/controllers/pages_controller.rb
app/views/pages/components.html.erb
config/routes.rb

added components page

---

app/models/comment.rb
app/models/good.rb
app/models/interest_tag.rb
app/models/post.rb
app/models/user.rb
app/models/zone.rb
app/models/zone_tag.rb
db/migrate/20181025122821_create_zones.rb
db/migrate/20181025123927_create_interest_tags.rb
db/migrate/20181025123944_create_zone_tags.rb
db/migrate/20181025124139_add_user_to_zones.rb
db/migrate/20181025124442_create_posts.rb
db/migrate/20181025124555_create_comments.rb
db/migrate/20181025124648_create_goods.rb
db/migrate/20181025124721_add_admin_to_users.rb
db/migrate/20181025131733_add_default_value_to_posts.rb
db/schema.rb
test/models/comment_test.rb
test/models/good_test.rb
test/models/interest_tag_test.rb
test/models/post_test.rb
test/models/zone_tag_test.rb
test/models/zone_test.rb

1. Added all models (except message) to DB.
2. Added validations to models
3. Faked some data in my local repo and it worked.

Add models to db

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_interest-card.scss
app/assets/stylesheets/config/_colors.scss
app/views/pages/components.html.erb

card interest component

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb
app/views/pages/components.html.erb

button, avatar

---

app/assets/javascripts/home.js
app/controllers/comments_controller.rb
app/controllers/posts_controller.rb
app/controllers/zones_controller.rb
app/models/post.rb
app/views/comments/new.html.erb
app/views/pages/home.html.erb
app/views/users/show.html.erb
app/views/zones/index.html.erb
config/routes.rb

Zone index

---

app/controllers/comments_controller.rb
app/views/comments/_comment.html.erb
app/views/comments/_form.html.erb
app/views/comments/create.js.erb
app/views/comments/new.html.erb
app/views/pages/home.html.erb

ajax for comments

---

app/assets/javascripts/home.js
app/javascript/packs/map.js
app/views/layouts/application.html.erb
app/views/zones/index.html.erb

1 Added leaflet on zone index page based on Googlemap API
2 Added circle and marker features

added leaflet on zone index page

---

app/views/components/_main_card.html.erb
app/views/components/_main_card_dropdown.html.erb
app/views/pages/home.html.erb
app/views/users/show.html.erb

1. Modified time display as XX min/hour/day ago.
2. Sorted posts on all pages using updated_at desc

modified time display and sorted posts as updated_at desc

---

app/javascript/packs/edit_post.js
app/views/pages/home.html.erb
app/views/posts/new.html.erb
app/views/posts/new.js.erb
app/views/posts/save.html.erb

Added post interest tags when creating a post. The tags are dynamic based on the zone chosen.

added post interest tags

---

app/views/posts/edit.html.erb

Modified edit post view as create post view.
Replaced placeholder by post content.
User can choose tags based on selected zone.

edit post view done

---

app/javascript/components/autocomplete.js
app/javascript/packs/map.js
app/javascript/packs/zone_map.js
app/views/zones/edit.html.erb
app/views/zones/new.html.erb

Added autocomplete feature on creation / edition of zone address.

added autocomplete

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/edit.html.erb
app/views/users/show.html.erb
db/migrate/20181106110249_add_background_url_to_users.rb
db/schema.rb

added background url to user

---

app/views/comments/_form.html.erb
app/views/comments/create.js.erb

automatically delete the input after submit

---

app/javascript/packs/map.js
app/javascript/packs/user_map.js
app/javascript/packs/zone_map.js
app/models/zone.rb
app/views/zones/edit.html.erb
app/views/zones/new.html.erb

Added placeholder on create/edit zone page

Radius 1000

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar_dashboard.scss
app/views/components/_main_card.html.erb
app/views/components/_main_card_dropdown.html.erb
app/views/pages/components.html.erb
app/views/pages/dashboard_data.html.erb

delete the share, structure for dashboard page two

---

app/assets/stylesheets/components/_comment-read.scss
app/assets/stylesheets/components/_comment.scss
app/views/comments/_comment.html.erb

name for comment

---

app/javascript/components/cross_interest_age.js
app/javascript/components/cross_interest_gender.js
app/javascript/components/sorting_age.js

color for dash

---

app/javascript/components/sorting_gender.js
app/javascript/components/sorting_interest.js

changed color
